version: '2'
services:
  kitchen-app:
    container_name: kitchen-app
    build: .
    command: "npm build --prod"
    ports:
      - 4200:4200
      - 49152:49152
    volumes:
      - .:/home/app/kitchen-app
      - /home/app/kitchen-app/node_modules
