version: '2'
services:
  kitchen-app:
    container_name: kitchenapp
    build: .
    command: "npm build --prod"
    ports:
      - 4200:4200
      - 49152:49152
    volumes:
      - .:/home/app/kitchenapp
      - /home/app/kitchenapp/node_modules
