version: '2'
services:
  kitchenapp:
    container_name: kitchenapp
    build: .
    command: "npm start -- --host=0.0.0.0"
    ports:
      - 4200:4200
      - 49152:49152
    volumes:
      - .:/home/app/kitchenapp
      - /home/app/kitchenapp/node_modules
